# Generated by Django 5.0.6 on 2024-10-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_users_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='BookUsers',
        ),
    ]
