# Generated by Django 5.0.6 on 2024-10-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_users_bookusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookUsers',
        ),
    ]
